// src/App.tsx
import { memo, useEffect, useRef, useState } from "react";
import {
  Badge,
  Box,
  Button,
  createTheme,
  Group,
  MantineProvider,
  Paper,
  Stack,
  Switch,
  Table,
  TextInput,
} from "@mantine/core";
import { EventRow } from "./EventRow";
import { get, last } from "lodash-es";

const theme = createTheme({
  components: {
    Badge: Badge.extend({
      defaultProps: {
        tt: "none",
      },
    }),
  },
});

const eventTypes: (keyof HTMLElementEventMap)[] = [
  "keydown",
  "keyup",
  "keypress",
  "input",
  "beforeinput",
  "beforematch",
];

const modifierKeys = [
  "Alt",
  "AltGraph",
  "CapsLock",
  "Control",
  "Fn",
  "Meta",
  "NumLock",
  "ScrollLock",
  "Shift",
  "Symbol",
  "SymbolLock",
];

export type TestEvent = {
  type: string;
  timeStamp: number;
  charCode: number;
  keyCode: number;
  which: number;
  modifiers: string;
  key: string;
  code: string;
  location: number;
  repeat: boolean;
  isComposing: boolean;
  inputType: string;
  data: string;
  delay: number;
};

export const App = memo(() => {
  const [botEvents, setBotEvents] = useState<TestEvent[]>([]);
  const [userEvents, setUserEvents] = useState<TestEvent[]>([]);
  const inputRef = useRef<HTMLInputElement>(null);
  const [mode, setMode] = useState<"bot" | "user">("bot");

  useEffect(() => {
    if (!inputRef.current) return;

    console.log("Registering event listeners");

    const listener = (event: Event) => {
      const testEvent: TestEvent = {
        type: event.type,
        timeStamp: event.timeStamp,
        charCode: get(event, "charCode", 0),
        keyCode: get(event, "keyCode", 0),
        which: get(event, "which", 0),
        modifiers: "",
        key: get(event, "key", ""),
        code: get(event, "code", ""),
        location: get(event, "location", 0),
        repeat: get(event, "repeat", false),
        isComposing: get(event, "isComposing", false),
        inputType: get(event, "inputType", ""),
        data: get(event, "data", ""),
        delay: 0,
      };

      if (event instanceof KeyboardEvent) {
        testEvent.modifiers = modifierKeys.filter((key) => event.getModifierState(key)).join(", ");
      }

      if (mode === "bot") {
        setBotEvents((prevEvents) => [
          ...prevEvents,
          {
            ...testEvent,
            delay: prevEvents.length > 0 ? testEvent.timeStamp - last(prevEvents)!.timeStamp : 0,
          },
        ]);
      } else {
        setUserEvents((prevEvents) => [
          ...prevEvents,
          {
            ...testEvent,
            delay: prevEvents.length > 0 ? testEvent.timeStamp - last(prevEvents)!.timeStamp : 0,
          },
        ]);
      }
    };

    const element = inputRef.current;

    eventTypes.forEach((type) => {
      element.addEventListener(type, listener);
    });

    return () => {
      eventTypes.forEach((type) => {
        element.removeEventListener(type, listener);
      });
    };
  }, [inputRef, mode]);

  const clearInput = () => {
    if (inputRef.current) {
      inputRef.current.value = "";
    }
  };

  const handleClear = () => {
    setBotEvents([]);
    clearInput();
  };

  useEffect(() => {
    clearInput();
  }, [mode]);

  return (
    <MantineProvider defaultColorScheme="auto" theme={theme}>
      <Box p="md">
        <Paper withBorder p="md">
          <Stack>
            <Group gap="xs">
              <TextInput id="input" flex={1} placeholder="Type here" ref={inputRef} />
              <Button color="red" onClick={handleClear}>
                Clear
              </Button>
              <Switch
                label={mode === "bot" ? "Bot Mode" : "User Mode"}
                checked={mode === "bot"}
                onChange={(event) => {
                  setMode(event.currentTarget.checked ? "bot" : "user");
                }}
              />
            </Group>

            <Table striped>
              <Table.Thead>
                <Table.Tr>
                  <Table.Th>#</Table.Th>
                  <Table.Th>Type</Table.Th>
                  <Table.Th>Timestamp</Table.Th>
                  <Table.Th>Delay</Table.Th>
                  <Table.Th>Char Code</Table.Th>
                  <Table.Th>Key Code</Table.Th>
                  <Table.Th>Which</Table.Th>
                  <Table.Th>Modifiers</Table.Th>
                  <Table.Th>Key</Table.Th>
                  <Table.Th>Code</Table.Th>
                  <Table.Th>Location</Table.Th>
                  <Table.Th>Repeat</Table.Th>
                  <Table.Th>Composing</Table.Th>
                  <Table.Th>Input Type</Table.Th>
                  <Table.Th>Data</Table.Th>
                </Table.Tr>
              </Table.Thead>

              <Table.Tbody>
                {(mode === "bot" ? botEvents : userEvents).map((event, index) => (
                  <EventRow key={`${mode}-${index}`} index={index} event={event} userEvent={userEvents[index]} />
                ))}
              </Table.Tbody>
            </Table>
          </Stack>
        </Paper>
      </Box>
    </MantineProvider>
  );
});

// src/App.svelte
<script lang="ts">
	import "./app.css";
	import EventRow from "./EventRow.svelte";
	import { Button } from "$lib/components/ui/button/index.js";
	import { Input } from "$lib/components/ui/input/index.js";
	import {
		ToggleGroup,
		ToggleGroupItem,
	} from "$lib/components/ui/toggle-group/index.js";
	import {
		Table,
		TableBody,
		TableHead,
		TableHeader,
		TableRow,
	} from "$lib/components/ui/table/index.js";


	const modifierKeys = [
		"Alt",
		"AltGraph",
		"CapsLock",
		"Control",
		"Fn",
		"Meta",
		"NumLock",
		"ScrollLock",
		"Shift",
		"Symbol",
		"SymbolLock"
	];

	type TestEvent = { 
		type: string;
		timeStamp: number;
		charCode: number;
		keyCode: number;
		which: number;
		modifiers: string;
		key: string;
		code: string;
		location: number;
		repeat: boolean;
		isComposing: boolean;
		inputType: string;
		data: string;
		delay: number
	 };

	let botEvents: TestEvent[] = $state([]);
	let userEvents: TestEvent[] = $state([]);
	let mode: "bot" | "user" = $state("bot");
	let inputValue = $state("");

	function getModifierState(event: KeyboardEvent): string {
		return modifierKeys.filter((key) => event.getModifierState(key as any)).join(", ");
	}

	function handleEvent(event: Event) {
		const testEvent: TestEvent = {
			type: event.type,
			timeStamp: event.timeStamp || 0,
			charCode: (event as any).charCode ?? 0,
			keyCode: (event as any).keyCode ?? 0,
			which: (event as any).which ?? 0,
			modifiers: "",
			key: (event as any).key ?? "",
			code: (event as any).code ?? "",
			location: (event as any).location ?? 0,
			repeat: (event as any).repeat ?? false,
			isComposing: (event as any).isComposing ?? false,
			inputType: (event as any).inputType ?? "",
			data: (event as any).data ?? "",
			delay: 0
		};

		if (event instanceof KeyboardEvent) {
			testEvent.modifiers = getModifierState(event);
		}

		if (mode === "bot") {
			const lastEvent = botEvents[botEvents.length - 1];

			testEvent.delay = lastEvent ? testEvent.timeStamp - lastEvent.timeStamp : 0;
			botEvents = [...botEvents, testEvent];
		} else {
			const lastEvent = userEvents[userEvents.length - 1];

			testEvent.delay = lastEvent ? testEvent.timeStamp - lastEvent.timeStamp : 0;
			userEvents = [...userEvents, testEvent];
		}
	}

	function clearInput() {
		inputValue = "";
	}

	function handleClear() {
		botEvents = [];
		userEvents = [];
		clearInput();
	}

	function handleKeydown(event: Event) {
		handleEvent(event);
	}

	function handleKeyup(event: Event) {
		handleEvent(event);
	}

	function handleInput(event: Event) {
		handleEvent(event);
	}

	function handleBeforeinput(event: Event) {
		handleEvent(event);
	}

	function handleBeforematch(event: Event) {
		handleEvent(event);
	}

	$effect(() => {
		mode;
		clearInput();
	});

	let currentEvents = $derived(mode === "bot" ? botEvents : userEvents);
</script>

<div class="min-h-screen bg-background p-4">
	<div class="max-w-7xl mx-auto">
		<div class="border rounded-lg p-4 bg-card shadow-sm">
			<!-- Header Controls -->
			<div class="flex items-center gap-2 mb-4">
				<Input
					id="input"
					type="text"
					placeholder="Type here"
					class="flex-1"
					bind:value={inputValue}
					onkeydown={handleKeydown}
					onkeypress={handleKeydown}
					onkeyup={handleKeyup}
					oninput={handleInput}
					onbeforeinput={handleBeforeinput}
					onbeforematch={handleBeforematch}
				/>
				<Button variant="destructive" onclick={handleClear}>Clear</Button>
				<ToggleGroup
					type="single"
					value={mode}
					onValueChange={(v) => {
						if (v) {
							mode = v as "bot" | "user";
						}
					}}
				>
					<ToggleGroupItem value="bot">Bot</ToggleGroupItem>
					<ToggleGroupItem value="user">User</ToggleGroupItem>
				</ToggleGroup>
			</div>

			<!-- Table -->
			<div class="overflow-x-auto">
				<Table>
					<TableHeader>
						<TableRow>
							<TableHead class="w-[50px] text-center">#</TableHead>
							<TableHead>Type</TableHead>
							<TableHead>Timestamp</TableHead>
							<TableHead>Delay</TableHead>
							<TableHead>Char Code</TableHead>
							<TableHead>Key Code</TableHead>
							<TableHead>Which</TableHead>
							<TableHead>Modifiers</TableHead>
							<TableHead>Key</TableHead>
							<TableHead>Code</TableHead>
							<TableHead>Location</TableHead>
							<TableHead>Repeat</TableHead>
							<TableHead>Composing</TableHead>
							<TableHead>Input Type</TableHead>
							<TableHead>Data</TableHead>
						</TableRow>
					</TableHeader>
					<TableBody>
						{#each currentEvents as event, index (index)}
							<EventRow index={index} {event} userEvent={userEvents[index]} />
						{/each}
					</TableBody>
				</Table>
			</div>
		</div>
	</div>
</div>
