// src/EventRow.tsx
import { Badge, Group, Table, Text, Tooltip } from "@mantine/core";
import { memo } from "react";
import { get } from "lodash-es";
import type { TestEvent } from "./App";

export type EventRowProps = {
  index: number;
  event: TestEvent;
  userEvent?: TestEvent;
};

const sortedKeys = [
  "type",
  "timeStamp",
  "delay",
  "charCode",
  "keyCode",
  "which",
  "modifiers",
  "key",
  "code",
  "location",
  "repeat",
  "isComposing",
  "inputType",
  "data",
] as (keyof TestEvent)[];

export const EventRow = memo(({ index, event, userEvent }: EventRowProps) => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const formatEventValue = (key: string, value: any) => {
    if (["timeStamp", "delay"].includes(key)) return value.toFixed(2);

    return value;
  };

  return (
    <Table.Tr>
      <Table.Td>{index + 1}</Table.Td>
      {sortedKeys.map((key) => {
        const value = formatEventValue(key, event[key]);
        const userValue = formatEventValue(key, get(userEvent, key, event[key]));

        return (
          <Table.Td key={key}>
            <Tooltip
              hidden={value === userValue || key === "timeStamp"}
              color="dark"
              withArrow
              label={
                <Group gap="xs">
                  <Text size="sm">{value}</Text>
                  <Text c="gray" size="sm">
                    -
                  </Text>
                  <Text size="sm">{userValue}</Text>
                </Group>
              }
            >
              <Group gap="xs">
                <Badge color={value !== userValue && key !== "timeStamp" ? "red" : "gray"}>{value}</Badge>
                {key === "keyCode" && !!value && <Badge color="gray">{String.fromCharCode(Number(value))}</Badge>}
              </Group>
            </Tooltip>
          </Table.Td>
        );
      })}
    </Table.Tr>
  );
});

// src/EventRow.svelte
<script lang="ts">
	import { Badge } from "$lib/components/ui/badge/index.js";
	import {
		TableRow,
		TableCell,
	} from "$lib/components/ui/table/index.js";

	type TestEvent = {
		type: string;
		timeStamp: number;
		charCode: number;
		keyCode: number;
		which: number;
		modifiers: string;
		key: string;
		code: string;
		location: number;
		repeat: boolean;
		isComposing: boolean;
		inputType: string;
		data: string;
		delay: number;
	};

	type Props = {
		index: number;
		event: TestEvent;
		userEvent?: TestEvent;
	};

	let { index, event, userEvent }: Props = $props();

	const sortedKeys: (keyof TestEvent)[] = [
		"type",
		"timeStamp",
		"delay",
		"charCode",
		"keyCode",
		"which",
		"modifiers",
		"key",
		"code",
		"location",
		"repeat",
		"isComposing",
		"inputType",
		"data",
	];

	function formatEventValue(key: string, value: any): any {
		if (["timeStamp", "delay"].includes(key)) return value.toFixed(2);
		return value;
	}
</script>

<TableRow>
	<TableCell class="text-center">{index + 1}</TableCell>
	{#each sortedKeys as key}
		{@const value = formatEventValue(key, event[key])}
		{@const userValue = formatEventValue(key, userEvent?.[key] ?? event[key])}
		{@const isDifferent = value !== userValue && key !== "timeStamp"}
		<TableCell>
			<div class="flex items-center gap-1">
				<Badge variant={isDifferent ? "destructive" : "secondary"}>
					{value}
				</Badge>
				{#if key === "keyCode" && !!value}
					<Badge variant="outline">
						{String.fromCharCode(Number(value))}
					</Badge>
				{/if}
			</div>
		</TableCell>
	{/each}
</TableRow>
